# Site settings
title: Good Artifact
email: goodartifact@gmail.com
description: "Free zine about art and nothingness. Based in Ottawa."
baseurl: ""
url: "http://localhost:4000/"

# Build settings
markdown: kramdown
permalink: pretty
